name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  upload-compose-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deliver Docker Compose file to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: production/

  run-docker-compose:
    runs-on: ubuntu-latest
    needs: upload-compose-file
    steps:
      - name: Run Docker Compose on production server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd production
            docker compose pull
            docker compose up -d
