name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger workflow når der pushes til main branch

jobs:
  upload-compose-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deliver Docker Compose file to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}  # Brug den private SSH-nøgle fra Secrets
          source: "docker-compose.yaml"
          target: production/

  run-docker-compose:
    runs-on: ubuntu-latest
    needs: upload-compose-file
    steps:
      - name: Run Docker Compose on production server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.PROD_SERVER_IP }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}  # Brug den private SSH-nøgle fra Secrets
          script: |
            # SSH til server og kør docker-compose kommandoer
            cd production
            docker compose pull
            docker compose up -d  # Kør docker i detached mode

  setup-ssh:
    runs-on: ubuntu-latest
    needs: run-docker-compose
    steps:
      - name: Setup SSH agent with private key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PROD_SERVER_SSH_KEY }}  # Brug den private SSH-nøgle fra GitHub Secrets

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ vars.PROD_SERVER_IP }} "echo SSH connection successful!" # Test SSH-forbindelsen
